### ISSUE TITLE
How to change Editor Theme

### ISSUE THREAD

**Issue by tahercoolguy** [Teradata/covalent-code-editor#28]
Really sorry for raising idiotic issue . I am not able to find how change theme of code editor Like from Light to Dark . Please Provide me with the snippets
thank you

**Comment by jeremysmartt** [comment]
Hello, to style the editor you can use the theme input like this:
`<td-code-editor theme="vs-dark"`

For a full list of the API for the td-code-editor see here:
https://github.com/Teradata/covalent-code-editor/blob/develop/docs/API.md

**Comment by tahercoolguy** [comment]
Thank you very much

**Comment by LoganDark** [comment]
Here's how to find the available themes:

![lol](https://puu.sh/Af9o9/94cff95e8a.png)

Because there is **no list on the docs page, even though, since you said there was, there should be**.

**Comment by kyleledbetter** [comment]
Well the `theme` API was here https://github.com/Teradata/covalent-code-editor/blob/develop/docs/API.md

and we use whatever comes with Monaco, just like we allow options directly from Monaco and we don't document all that since they do...

that being said their docs are lacking and we could add some of them in our docs
